# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script:
    echo $(System.DefaultWorkingDirectory)
  displayName: 'Show path of directory'

- script:
    echo cd $(System.DefaultWorkingDirectory)
    echo ls -la 
  displayName: 'Show contents of dir'

- task: Bash@3
  displayName: 'Show all sys env variables'
  inputs:
    targetType: 'inline'
    script: 'env | sort'

- task: Bash@3
  displayName: 'Show files in $(BUILD_SOURCESDIRECTORY)'
  inputs: 
    targetType: 'inline'
    script: 'ls -la $(BUILD_SOURCESDIRECTORY)'

- task: Bash@3
  displayName: 'Show contents of Manifest file'
  inputs:
   targetType: 'inline'
   script: 'cat $(BUILD_SOURCESDIRECTORY)/azure-vote-all-in-one-redis.yaml'