apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: kjidevazurevotingappredis 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kjidevazurevotingappredis 
    spec:
      containers:
        - name: kjidevazurevotingappredis 
          image: demodemocr.azurecr.io/kjidevazurevotingappredis
          ports:
          - containerPort: 80